### ISSUE TITLE
npm install from frontend gives Error: The package reflect-metadata@0.1.3 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by maharsh** [northernv/mastering-mean#1]
Running npm install in frontend package gives following error.

Error: The package reflect-metadata@0.1.3 does not satisfy its siblings' peerDependencies requirements!

This error details says

error peerinvalid Peer angular2@2.0.0-beta.9 wants reflect-metadata@0.1.2

Looks like in frontend/package.json, "reflect-metadata": "0.1.3" , causes issue. 

After changing to  "reflect-metadata": "0.1.2". It works fine for me.

Kindly look into it.

After changing frontend/package.json

**Comment by shanestillwell** [comment]
Thanks. From my testing it was working just fine even with this error message.
