### ISSUE TITLE
npm install doesn't seem to work

### ISSUE THREAD

**Issue by nelsonlho** [northernv/mastering-mean#2]
the last few lines after typing in `npm install -dd`:
`npm verb correctMkdir /Users/nho/.npm correctMkdir not in flight; initializing
npm verb afterAdd /Users/nho/.npm/string-replace-webpack-plugin/0.0.3/package/package.json written
npm verb afterAdd /Users/nho/.npm/socket.io-client/1.4.6/package/package.json written
npm verb afterAdd /Users/nho/.npm/style-loader/0.13.1/package/package.json written
npm verb afterAdd /Users/nho/.npm/sass-loader/3.2.0/package/package.json written
npm verb afterAdd /Users/nho/.npm/reflect-metadata/0.1.3/package/package.json written
npm verb afterAdd /Users/nho/.npm/autoprefixer/6.3.6/package/package.json written
npm verb afterAdd /Users/nho/.npm/url-loader/0.5.7/package/package.json written
npm verb afterAdd /Users/nho/.npm/protractor/3.3.0/package/package.json written
npm verb afterAdd /Users/nho/.npm/webpack-dev-server/1.14.1/package/package.json written
npm verb afterAdd /Users/nho/.npm/zone.js/0.5.15/package/package.json written
npm verb afterAdd /Users/nho/.npm/rxjs/5.0.0-beta.2/package/package.json written
npm verb afterAdd /Users/nho/.npm/webpack/1.13.1/package/package.json written
npm verb afterAdd /Users/nho/.npm/angular2/2.0.0-beta.9/package/package.json written
npm verb afterAdd /Users/nho/.npm/html-webpack-plugin/2.21.0/package/package.json written
npm verb afterAdd /Users/nho/.npm/babel-plugin-angular2-annotations/5.1.0/package/package.json written
npm verb afterAdd /Users/nho/.npm/standard-loader/3.0.0/package/package.json written
npm verb afterAdd /Users/nho/.npm/standard/6.0.8/package/package.json written`

**Comment by shanestillwell** [comment]
What version of npm? Have you tried running with the `sudo` command. It sounds like a local npm issue.

**Comment by nelsonlho** [comment]
had to resolve to what the other person did in the first issue
